Update common bash function script

diff --git a/binaries/.local/bin/common b/binaries/.local/bin/common
--- a/binaries/.local/bin/common
+++ b/binaries/.local/bin/common
@@ -1,24 +1,46 @@
-#!/usr/bin/env zsh
+#!/usr/bin/env bash
+set -o errexit  # exit immediately upon error
+set -o pipefail # surface errors in pipes
+set -o nounset  # prohibit undefined variables
+IFS=$'\n\t'     # split on newline or tab by default
 
-set -o errexit
-set -o pipefail
+readonly _INT_REGEX="^[0-9]+$"
+readonly _FLOAT_REGEX="^[0-9]+\.[0-9]+$"
 
-FLOAT=^[0-9]*\.?[0-9]+$
-INT=^[0-9]+$
+_depend_on() {
+    for dependency in "$@"; do
+        type "$dependency" &> /dev/null || _error_exit "missing dependency: ${dependency}"
+    done
+}
+
+_exit() {
+    echo "${1:-}"
+    exit 0
+}
 
 _error_exit() {
-    echo "$1" >&2
+    echo "${1:-"An unknown error occurred"}" >&2
     exit 1
 }
 
-_depend_on() {
-    type "$1" &>/dev/null || _error_exit "missing dependency: ${1}"
+_is_int() {
+    [[ "$1" =~ $_INT_REGEX ]]
 }
 
 _require_int() {
-    [[ $1 =~ $INT ]] || _error_exit ${2:-"Expected an integer: $1"}
+    _is_int "$1" || _error_exit "${2:-"expected an integer"}"
+}
+
+_is_float() {
+    [[ "$1" =~ $_FLOAT_REGEX ]]
 }
 
 _require_float() {
-    [[ $1 =~ $FLOAT ]] || _error_exit ${2:-"Expected a float: $1"}
+    _is_float "$1" || _error_exit "${2:-"expected a float"}"
+}
+
+_string_contains() {
+    local output="${1:-}"
+    local search_term="${2:-}"
+    [[ "$output" =~ .*"$search_term".* ]]
 }
